# Generated by Django 3.0.8 on 2020-09-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTwo', '0004_auto_20200518_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='portfolio_site',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
