# Generated by Django 3.0.8 on 2020-09-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTwo', '0005_auto_20200905_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='unique_id',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
    ]
