# Generated by Django 3.0.8 on 2020-09-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTwo', '0006_userprofileinfo_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='unique_id',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
